
Traceback (most recent call last):
> File "tests/exceptions/source/backtrace/enqueue.py", line 9, in <module>
    1 / 0
ZeroDivisionError: division by zero
