
Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/frame_values_backward.py", line 24, in <module>
    c(k)
  File "tests/exceptions/source/backtrace/frame_values_backward.py", line 21, in c
    b(n - 1)
> File "tests/exceptions/source/backtrace/frame_values_backward.py", line 17, in b
    a(n - 1)
  File "tests/exceptions/source/backtrace/frame_values_backward.py", line 13, in a
    1 / n
ZeroDivisionError: division by zero
