
Traceback (most recent call last):
> File "tests/exceptions/source/backtrace/missing_attributes_traceback_objects.py", line 38, in <module>
    foo()
  File "tests/exceptions/source/backtrace/missing_attributes_traceback_objects.py", line 18, in foo
    div(a, b)
  File "tests/exceptions/source/backtrace/missing_attributes_traceback_objects.py", line 14, in div
    x / y
ZeroDivisionError: division by zero
